<a href="https://colab.research.google.com/github/upskilleralok07/aloksharma1/blob/main/nlp_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("praveengovi/emotions-dataset-for-nlp")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'emotions-dataset-for-nlp' dataset.
Path to dataset files: /kaggle/input/emotions-dataset-for-nlp


In [ ]:
df=pd.read_csv('train.txt',sep=';',header=None,names=['text','emotion'])


In [ ]:
df.head(

)

text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [ ]:
unique_emotions=df['emotion'].unique()
emotion_numbers={}
i=0
for emotion in unique_emotions:
    emotion_numbers[emotion]=i
    i+=1

df['emotion']=df['emotion'].map(emotion_numbers)

In [ ]:
df

text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [ ]:
df['text']=df['text'].apply(lambda x:x.lower())


In [ ]:
import string
import pandas as pd

# Function to remove punctuation from a text string
def remove_punctuation(text):
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)

# The previous application of this function seemed to have removed all text.
# Let's temporarily skip applying it to verify the text content after reloading.
# If the text is still there, we'll re-evaluate this function.
# df['text'] = df['text'].apply(remove_punctuation)

# For now, let's print the head to see the text after just lowercasing.
print("Current state of 'text' column after reloading and lowercasing:")
print(df['text'].head().to_string())


Current state of 'text' column after reloading and lowercasing:
0                              i didnt feel humiliated
1    i can go from feeling so hopeless to so damned...
2     im grabbing a minute to post i feel greedy wrong
3    i am ever feeling nostalgic about the fireplac...
4                                 i am feeling grouchy


In [ ]:
df

text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [ ]:
# This cell used to apply remove_numbers, but we are temporarily skipping it to restore text.
# def remove_numbers(txt):
#   new=""
#   for i in txt:
#     if not i.isdigit():
#       new+=i
#   return new
# df['text']=df['text'].apply(remove_numbers)


In [ ]:
# This cell used to apply remove_numbers, but we are temporarily skipping it to restore text.
# def remove_numbers(txt):
#   new=""
#   for i in txt:
#     if not i.isdigit():
#       new+=i
#   return new
# df['text']=df['text'].apply(remove_numbers)


In [ ]:
# This cell used to apply remove_emojis, but we are temporarily skipping it to restore text.
# def remove_emojis(txt):
#   new=""
#   for i in txt:
#     if not i.isascii():
#       new+=i
#   return new
# df['text']=df['text'].apply(remove_emojis)


In [ ]:
import string
import re

def remove_numbers_and_emojis(text):
    # Remove numbers
    text_no_numbers = re.sub(r'\d+', '', text)

    # Remove emojis using emoji unicode ranges
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F700-\U0001F77F"  # alchemical symbols
                           u"\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
                           u"\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
                           u"\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
                           u"\U0001FA00-\U0001FA6F"  # Chess Symbols
                           u"\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
                           u"\U00002702-\U000027B0"  # Dingbats
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)

    text_no_emojis = emoji_pattern.sub(r'', text_no_numbers)

    # Remove punctuation
    translator = str.maketrans('', '', string.punctuation)
    clean_text = text_no_emojis.translate(translator)

    return clean_text

# Applying on DataFrame column 'text'
import pandas as pd

# Example dataframe
# df = pd.DataFrame({'text': ['Hello 😊 123!', 'I love AI ❤️ 456']})

df['text'] = df['text'].apply(remove_numbers_and_emojis)


In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
df

text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [ ]:
stop_words=set(stopwords.words('english'))
len(stop_words)

198

In [ ]:
def remove_stopwords(txt):
  words=txt.split()
  cleaned=[]
  for word in words:
    if word not in stop_words:
      cleaned.append(word)
  return' '.join(cleaned)
df['text']=df['text'].apply(remove_stopwords)

In [ ]:
# Importing CountVectorizer from sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# Sample text data
documents = [
    "I love pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great"
]

# Initialize CountVectorizer
vectorizer = CountVectorizer()
vectorizer_a = TfidfVectorizer()
# Fit and transform the documents
X = vectorizer.fit_transform(documents)
X = vectorizer_a.fit_transform(documents)
# Display the vocabulary and Bag of Words matrix
print("Vocabulary:", vectorizer.get_feature_names_out())
print("\nBoW Matrix:\n", X.toarray())


Vocabulary: ['best' 'great' 'is' 'love' 'pasta' 'pizza' 'the']

BoW Matrix:
 [[0.         0.         0.         0.70710678 0.         0.70710678
  0.        ]
 [0.55528266 0.         0.43779123 0.         0.         0.43779123
  0.55528266]
 [0.         0.         0.         0.70710678 0.70710678 0.
  0.        ]
 [0.         0.66767854 0.52640543 0.         0.52640543 0.
  0.        ]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df['text'],df['emotion'],random_state=42,test_size=0.33)

In [ ]:
# Importing CountVectorizer from sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer


# Initialize CountVectorizer
vectorizer = CountVectorizer()

# Fit the vectorizer on the training data and transform it
X_train1 = vectorizer.fit_transform(x_train)

# Transform the test data using the *same* fitted vectorizer
X_test1 = vectorizer.transform(x_test)


In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
nb=MultinomialNB()
nb.fit(X_train1,y_train)

MultinomialNB()

In [ ]:
pred_nb=nb.predict(X_test1)
print(accuracy_score(y_test,pred_nb))
print(confusion_matrix(y_test,pred_nb))

0.7647727272727273
[[1460   18    4    0    6   71]
 [ 141  422    0    0   19   83]
 [  60    9  119    0    8  281]
 [  61    2    4   13   21   92]
 [ 159   26    1    0  342  107]
 [  53    6    4    0    6 1682]]


In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(max_iter=1000)
lr.fit(X_train1,y_train)

LogisticRegression(max_iter=1000)

In [ ]:
pred_lr=lr.predict(X_test1)
print(accuracy_score(y_test,pred_lr))
print(confusion_matrix(y_test,pred_lr))

0.887689393939394
[[1447   40   12    2   20   38]
 [  53  565    1    3   17   26]
 [   5    3  364    1    4  100]
 [  10    1    2  139   25   16]
 [  34   28    2   15  521   35]
 [  31    6   51    6    6 1651]]


In [ ]:
# Example: Save your trained model
import joblib

joblib.dump(lr, 'lr.pkl')


['lr.pkl']